debug: true
########################################################
### spring 相关配置
########################################################
spring:
  profiles:
    active: druid
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  boot:
    admin:
      url: http://localhost:${server.port}
  application :
    name: aishanghua_app_api
  mvc:
    favicon :
      enabled: false
    static-path-pattern: /**
  #上传大小限制
  http:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 100Mb
  # thymeleaf 相关配置
  thymeleaf :
    cache: false

  jackson :
    mapper:
      sort_properties_alphabetically: true
    property-naming-strategy: LOWER_CAMEL_CASE
    serialization:
      indent_output: true

  ########################################################
  ### datasource
  ########################################################
  datasource :
    url: jdbc:mysql://rm-uf62kcr0wm95wj961vo.mysql.rds.aliyuncs.com:3306/hxx-prod?characterEncoding=UTF-8&allowMultiQueries=true
    username: hxx_prod
    password: prod!@#$%^=368&huaxiaoxia

  ########################################################
  ###redis
  ########################################################
  redis :
    host: 47.100.179.59
    password: prodHuaxiaoxia3688
    database: 10
    port: 6379
    timeout: 1000
    maxTotal: 500
    maxIdle: 500
    maxWaitMillis: 2

  #############定义日志输出色彩
  output:
    ansi:
      enabled: DETECT

  mail:
    server: false
    host: smtp.exmail.qq.com
    username: 2017732276@qq.com
    password: asd123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

########################################################
### web访问端口配置
########################################################
server:
  context-path: /
  port: 8084

########################################################
### mybatis配置
########################################################
mybatis :
  mapper-locations: classpath:/mapping/*.xml,classpath:/mapping2/*.xml
  configuration:
    mapUnderscoreToCamelCase: true


########################################################
### logback 配置
########################################################
logging:
  level: debug
  config: classpath:config/logback.xml

########################################################
#####################其它配置###########################
########################################################


qn_ak: I2oHQs8pTLQA8ng9QNuBUwCANHgFk0p5G8YRvqUr
qn_sk: hIIaCs4-YIKMdZCcigvwMzuCN58I_ZuB-bYFIsB_
qn_bucket: hxx-prod
domainOfBucket: prod-img.hxx368.com

# face++ 接口参数
faceid:
  app_key: X0bDog-Vv2rBSakxCvH7VyWvEq9Q3QmP
  app_secret: UN2AOA7syx-MxCvuJx8Xg03Gp5_-gtNt
  # 人脸比对接口地址
  face_matching: https://api.megvii.com/faceid/v2/verify
  ocr_url: https://api.faceid.com/faceid/v1/ocridcard

web:
  upload-path: /mnt/upload/