########################################################
### spring 相关配置
########################################################
spring:
  profiles:
    active: druid
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  boot:
    admin:
      url: http://localhost:${server.port}
  application :
    name: quhuigou_back
  mvc:
    favicon :
      enabled: false
    static-path-pattern: /**
  #上传大小限制
  http:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 100Mb
  # thymeleaf 相关配置
  thymeleaf :
    cache: false

  jackson :
    mapper:
      sort_properties_alphabetically: true
    property-naming-strategy: LOWER_CAMEL_CASE
    serialization:
      indent_output: true

  ########################################################
  ### datasource
  ########################################################
  datasource:
    url: jdbc:mysql://47.92.234.213:3306/hxx-test?characterEncoding=UTF-8&allowMultiQueries=true
    username: xiaoxia-test
    password: Hxiaoxia2468
  ########################################################
  ###redis
  ########################################################
  redis :
    host: 47.92.234.213
    password: xiaoxia2468
    database: 3
    port: 6379
    timeout: 1000
    maxTotal: 500
    maxIdle: 500
    maxWaitMillis: 2

  #############定义日志输出色彩
  output:
    ansi:
      enabled: DETECT

  mail:
    server: false
    host: smtp.exmail.qq.com
    username: system01@souyijie.com
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

########################################################
### mybatis配置
########################################################
mybatis :
  mapper-locations: classpath:/mapping/*.xml,classpath:/mapping2/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    callSettersOnNulls: true
########################################################
#####################其它配置###########################
########################################################

qn_ak: I2oHQs8pTLQA8ng9QNuBUwCANHgFk0p5G8YRvqUr
qn_sk: hIIaCs4-YIKMdZCcigvwMzuCN58I_ZuB-bYFIsB_
qn_bucket: hxx-dev
domainOfBucket: dev-img.hxx368.com
# face++ 接口参数
faceid:
  app_key: SiUhQXdtPweOFnZQvgWGQaUcYRNGWZ1D
  app_secret: elVO4kNy5SVrP9kB40DGw1fTzIe2hQS6
  # 人脸比对接口地址
  face_matching: https://api.megvii.com/faceid/v2/verify
  ocr_url: https://api.faceid.com/faceid/v1/ocridcard

logging:
  level: debug
  config: classpath:config/logback.xml

server:
  context-path: /
  port: 8085

web:
  upload-path: upload/
